pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps { checkout poll: true, changelog: true, // Выполняем команду checkout для извлечения исходных кодов из репозитория.
                            scm: [
                                $class: 'GitSCM', // Указываем, что используем Git в качестве системы контроля версий.
                                branches: [[name: '*/main' ]], // Указываем ветку для checkout.
                                extensions: [],
                                userRemoteConfigs: [[
                                    //credentialsId: '' ,  Идентификатор учетных данных для доступа к репозиторию.
                                    url: "https://github.com/Bruno44rus/jenkins_practise.git" // URL репозитория.
                                ]]
                            ]
    }
    stage('build and deploy') 
      steps {
        sh 'docker compose down || true'
        sh 'docker compose up -d --build'
      }
    }
  }
}