pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps { checkout scm: [$class: 'GitSCM',
          userRemoteConfigs: [[url: 'git@https://github.com/Bruno44rus/jenkins_practise.git'
                              //credentialsId: 'myCredId'
                              ]],
                              branches: [[name: 'refs/heads/main']]
        ], poll: true
    }
    }
    stage('build and deploy'){ 
      steps {
        sh 'docker-compose -f ./_devops/docker-compose/docker-compose.yml down || true'
        sh 'docker-compose -f ./_devops/docker-compose/docker-compose.yml up -d'
      }
    }
  }
}
